#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/s/cartographer_navigation-main/cartographer_location/cartographer_ws/devel_isolated/cartographer_ros_msgs:/home/s/turtle/devel_isolated/turtlebot3_teleop:/home/s/turtle/devel_isolated/turtlebot3_slam:/home/s/turtle/devel_isolated/turtlebot3_simulations:/home/s/turtle/devel_isolated/turtlebot3_navigation:/home/s/turtle/devel_isolated/turtlebot3_fake:/home/s/turtle/devel_isolated/turtlebot3_example:/home/s/turtle/devel_isolated/turtlebot3_bringup:/home/s/turtle/devel_isolated/turtlebot3_msgs:/home/s/turtle/devel_isolated/turtlebot3_gazebo:/home/s/turtle/devel_isolated/turtlebot3_description:/home/s/turtle/devel_isolated/turtlebot3:/home/s/carto723/devel_isolated/cartographer_rviz:/home/s/carto723/devel_isolated/cartographer_ros:/home/s/carto723/devel_isolated/cartographer_ros_msgs:/opt/ros/noetic:/home/s/cartographer_navigation-main/cartographer_location/cartographer_ws/devel_isolated/cartographer:/home/s/carto713/devel_isolated/ceres-solver:/home/s/carto713/devel_isolated/cartographer:/home/s/carto723/devel_isolated/cartographer'
export LD_LIBRARY_PATH='/home/s/turtle/devel_isolated/turtlebot3_teleop/lib:/home/s/turtle/devel_isolated/turtlebot3_slam/lib:/home/s/turtle/devel_isolated/turtlebot3_navigation/lib:/home/s/turtle/devel_isolated/turtlebot3_fake/lib:/home/s/turtle/devel_isolated/turtlebot3_example/lib:/home/s/turtle/devel_isolated/turtlebot3_bringup/lib:/home/s/turtle/devel_isolated/turtlebot3_msgs/lib:/home/s/turtle/devel_isolated/turtlebot3_gazebo/lib:/home/s/turtle/devel_isolated/turtlebot3_description/lib:/home/s/carto723/devel_isolated/cartographer_rviz/lib:/home/s/carto723/devel_isolated/cartographer_ros/lib:/home/s/carto723/devel_isolated/cartographer_ros_msgs/lib:/opt/ros/noetic/lib:/home/s/cartographer_navigation-main/cartographer_location/cartographer_ws/devel_isolated/cartographer/lib:/home/s/cartographer_navigation-main/cartographer_location/cartographer_ws/devel_isolated/cartographer/lib/x86_64-linux-gnu:/home/s/carto713/devel_isolated/ceres-solver/lib:/home/s/carto713/devel_isolated/cartographer/lib:/home/s/carto723/devel_isolated/cartographer/lib'
export PATH='/opt/ros/noetic/bin:/home/s/cartographer_navigation-main/cartographer_location/cartographer_ws/devel_isolated/cartographer/bin:/home/s/carto713/devel_isolated/cartographer/bin:/home/s/carto723/devel_isolated/cartographer/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/s/turtle/devel_isolated/turtlebot3_teleop/lib/pkgconfig:/home/s/turtle/devel_isolated/turtlebot3_slam/lib/pkgconfig:/home/s/turtle/devel_isolated/turtlebot3_navigation/lib/pkgconfig:/home/s/turtle/devel_isolated/turtlebot3_fake/lib/pkgconfig:/home/s/turtle/devel_isolated/turtlebot3_example/lib/pkgconfig:/home/s/turtle/devel_isolated/turtlebot3_bringup/lib/pkgconfig:/home/s/turtle/devel_isolated/turtlebot3_msgs/lib/pkgconfig:/home/s/turtle/devel_isolated/turtlebot3_gazebo/lib/pkgconfig:/home/s/turtle/devel_isolated/turtlebot3_description/lib/pkgconfig:/home/s/carto723/devel_isolated/cartographer_rviz/lib/pkgconfig:/home/s/carto723/devel_isolated/cartographer_ros/lib/pkgconfig:/home/s/carto723/devel_isolated/cartographer_ros_msgs/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/home/s/cartographer_navigation-main/cartographer_location/cartographer_ws/devel_isolated/cartographer/lib/pkgconfig:/home/s/cartographer_navigation-main/cartographer_location/cartographer_ws/devel_isolated/cartographer/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/s/turtle/devel_isolated/turtlebot3_teleop/lib/python3/dist-packages:/home/s/turtle/devel_isolated/turtlebot3_example/lib/python3/dist-packages:/home/s/turtle/devel_isolated/turtlebot3_msgs/lib/python3/dist-packages:/home/s/carto723/devel_isolated/cartographer_ros_msgs/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/home/s/cartographer_navigation-main/cartographer_location/cartographer_ws/devel_isolated/cartographer/lib/python3/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/s/cartographer_navigation-main/cartographer_location/cartographer_ws/devel_isolated/cartographer_ros_msgs/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/s/cartographer_navigation-main/cartographer_location/cartographer_ws/src/cartographer_ros/cartographer_ros_msgs:$ROS_PACKAGE_PATH"